services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://root:example@mongo:27017/admin
      DB_NAME: testDB
    volumes:
      - .:/app
      - /app/node_modules
    command: node ./bin/www
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
